# Generated by Django 5.1.4 on 2025-01-21 16:53

import crud_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('image', models.ImageField(default=None, null=True, upload_to=crud_app.models.student_directory_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
