# Generated by Django 5.1.4 on 2024-12-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='extra_field',
        ),
    ]
