# Generated by Django 5.1.4 on 2025-01-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
    ]
