# Generated by Django 5.1.4 on 2025-01-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationApp', '0002_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_model', models.ManyToManyField(to='relationApp.carmodel')),
            ],
        ),
    ]
