# Generated by Django 5.1.4 on 2025-01-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationApp', '0003_fueltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='car_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationApp.carcompany'),
        ),
    ]
