# Generated by Django 5.1.4 on 2025-01-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationApp', '0005_alter_ceo_car_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='car_model',
            new_name='car_models',
        ),
    ]
