# Generated by Django 5.1.4 on 2025-01-30 06:38

import studentsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=studentsapp.models.student_directory_name, validators=[studentsapp.models.validate_image_file]),
        ),
    ]
